trigger:
  branches:
    exclude:
      - "*"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: MasteringLinuxDev # Link to the variable group "MasteringLinuxDev"
  - name: resourceGroupName
    value: "rgMasteringLinux"
  - name: location
    value: "northeurope"
  - name: virtualMachineName
    value: "vmCentOsFresh"
  - name: networkSecurityGroupName
    value: "vmCentOsFresh-nsg"

steps:
  - script: |
      echo $(resourceGroupName)
      echo $(location)

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az group create --name $(resourceGroupName) --location "$(location)"

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "ServicePrincipalHotmail"
      subscriptionId: $(subscriptionId)
      action: "Create Or Update Resource Group"
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: "URL of the file"
      csmFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/.azure/vmCentOsFresh/template.json"
      csmParametersFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/.azure/vmCentOsFresh/parameters.json"
      deploymentMode: "Incremental"
      deploymentName: "DeployPipelineTemplate"
      overrideParameters: " -location $(location)
        -adminPassword $(adminPassword)
        -virtualMachineName  $(virtualMachineName)"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az network nsg rule create \
          --resource-group $(resourceGroupName) \
          --nsg-name $(networkSecurityGroupName) \
          --name AllowPort80 \
          --access Allow \
          --protocol Tcp \
          --direction Inbound \
          --priority 100 \
          --source-address-prefix "*" \
          --source-port-range "*" \
          --destination-address-prefix "*" \
          --destination-port-range 80

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az vm extension set \
          --publisher Microsoft.Azure.Extensions \
          --version 2.0 \
          --name CustomScript \
          --vm-name $(virtualMachineName) \
          --resource-group $(resourceGroupName) \
          --settings '{
            "commandToExecute": "sudo yum install -y yum-utils && \
                                 sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
                                 sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
                                 sudo systemctl start docker"
          }'
