trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: MasteringLinuxDev # Link to the variable group "MasteringLinuxDev"
  - name: resourceGroupName
    value: "rgMasteringLinux"
  - name: location
    value: "northeurope"

steps:
  - script: echo $(adminPassword)

  - script: echo $(resourceGroupName)

  - script: echo $(location)

  - script: echo "begin cli"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az group create --name $(resourceGroupName) --location "$(location)"

  - script: echo "begin template"

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "ServicePrincipalHotmail"
      subscriptionId: "36a7d4b6-e14b-4e56-93b6-f04b550d58f6"
      action: "Create Or Update Resource Group"
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: "URL of the file"
      csmFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/Templates/vmCentOsFresh/template.json"
      csmParametersFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/Templates/vmCentOsFresh/parameters.json"
      deploymentMode: "Incremental"
      deploymentName: "DeployPipelineTemplate"
      overrideParameters: "-location $(location) -adminPassword $(adminPassword)"
