trigger:
  branches:
    exclude:
      - "*"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: MasteringLinuxDev # Link to the variable group "MasteringLinuxDev"
  - name: resourceGroupName
    value: "rgMasteringLinux"
  - name: location
    value: "northeurope"
  - name: vmName
    value: "vmCentOsFresh"

steps:
  - script: |
      echo $(resourceGroupName)
      echo $(location)

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az group create --name $(resourceGroupName) --location "$(location)"

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: "ServicePrincipalHotmail"
      subscriptionId: $(subscriptionId)
      action: "Create Or Update Resource Group"
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: "URL of the file"
      csmFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/.azure/vmCentOsFresh/template.json"
      csmParametersFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/MasteringLinux/main/.azure/vmCentOsFresh/parameters.json"
      deploymentMode: "Incremental"
      deploymentName: "DeployPipelineTemplate"
      overrideParameters: " -location $(location)
        -adminPassword $(adminPassword)
        -vmName  $(vmName)"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "ServicePrincipalHotmail"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az vm extension set \ 
        --publisher Microsoft.Azure.Extensions \  
        --version 2.0 \ 
        --name CustomScript \ 
        --vm-name $(vmName) \ 
        --resource-group $(resourceGroupName) \ 
        --settings '{"commandToExecute":"sudo yum install -y yum-utils && \
                          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
                          sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
                          sudo systemctl start docker"}'
