trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Azure CLI Login'
  inputs:
    azureSubscription: 'MyAzureSubscription' # Replace 'MyAzureSubscription' with your Azure subscription name or service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name MyACR' # Replace 'MyACR' with the name of your Azure Container Registry

- task: AzureCLI@2
  displayName: 'Deploy Container Instance'
  inputs:
    azureSubscription: 'MyAzureSubscription' # Replace 'MyAzureSubscription' with your Azure subscription name or service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container create \
        --resource-group MyResourceGroup \
        --name mycontainer \
        --image myacr.azurecr.io/myimage:latest \
        --cpu 1 \
        --memory 1 \
        --registry-login-server myacr.azurecr.io \
        --registry-username $(ACR_USERNAME) \
        --registry-password $(ACR_PASSWORD) \
        --dns-name-label mycontainerdns \
        --ports 80
